In [48]:
import pandas as pd
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [49]:
data = pd.read_excel("iris-train.xlsx")

In [50]:
data.head()

   Sapellength  SapelWidth  patellength  patelwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [51]:
x = data.iloc[:, :-1]

In [52]:
x

     Sapellength  SapelWidth  patellength  patelwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [53]:
y = data.iloc[:, -1]

In [54]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [55]:
model = RandomForestClassifier()

In [56]:
x.values

array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 2.6, 6.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.1, 3. , 5.9, 2.1],
       [7. , 3.2, 4.7, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.8, 3.2, 5.9, 2.3],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [6.7, 2.5, 5.8, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 3.2, 5.3, 2.3],
       [6.4, 3.2, 4.5, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.4, 2.7, 5.3, 1.9],
       [6.3, 3.4, 5.6, 2.4],
       [6.3, 3.3, 6. , 2.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [6.3, 2.5, 4.9, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [6.2, 3.4, 5.4, 2.3],
       [6.2, 2.9, 4.3, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6.2, 2.2, 4.5, 1.5],
       [6.1, 3. , 4.9, 1.8],
       [6.1, 3. , 4.6, 1.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6. , 3.4, 4.5, 1.6],
       [6. , 3. , 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [6. , 2.2, 5. , 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.9, 3.2, 4.8, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.7, 4.1, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 2.5, 5. , 2. ],
       [5.6, 3. , 4.5, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [4.7, 3.2, 1.6, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.3, 3. , 1.1, 0.1]])

In [57]:
model.fit(x,y)

RandomForestClassifier()

In [58]:
prediction = model.predict([[5.4,	3,	4.5,	1.5]])

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [59]:
prediction

array(['Iris-versicolor'], dtype=object)

In [60]:
datatest = pd.read_excel("iris - test.xlsx")

In [61]:
x_test = datatest.iloc[:, :-1]

In [62]:
predictions = model.predict(x_test.values)

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [63]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [64]:
y_test = datatest.iloc[:,-1]

In [65]:
y_test

0     Iris-versicolor
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5     Iris-versicolor
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14    Iris-versicolor
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23    Iris-versicolor
24    Iris-versicolor
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29     Iris-virginica
30    Iris-versicolor
31        Iris-setosa
32        Iris-setosa
33        Iris-setosa
Name: class, dtype: object

In [66]:
actual = y_test.values

In [67]:
count = 0
for i in range(0, len(actual)):
    if actual[i] == predictions[i]:
        count = count + 1
    print((count* 100)/len(actual))

2.9411764705882355
5.882352941176471
8.823529411764707
11.764705882352942
14.705882352941176
17.647058823529413
20.58823529411765
23.529411764705884
26.470588235294116
29.41176470588235
32.35294117647059
35.294117647058826
38.23529411764706
41.1764705882353
44.11764705882353
47.05882352941177
50.0
52.94117647058823
55.88235294117647
58.8235294117647
61.76470588235294
64.70588235294117
67.6470588235294
70.58823529411765
73.52941176470588
76.47058823529412
79.41176470588235
82.3529411764706
85.29411764705883
85.29411764705883
88.23529411764706
91.17647058823529
94.11764705882354
97.05882352941177

Measuring Accuracy of our Predictions

When we build a machine learning model, especially a classification model (which predicts categories like "spam" or "not spam", "dog" or "cat"), it's important to measure how well the model is performing.

One of the most basic ways to evaluate a classification model is accuracy.

What is Accuracy?
In simple terms, accuracy tells us how often the model was right.

If you gave your model 100 questions to answer, and it got 90 of them correct, its accuracy would be:

Accuracy = Correct Predictions / Total Predictions = 90 / 100 = 90%
So, accuracy is just the fraction of predictions the model got right.

Evaluating Accuracy
Accuracy = (Correct Predictions) / (Total Predictions)

This is the simplest and most intuitive way to check if the model is doing a good job.